### PR TITLE
Changed comment in dna.py

### LINKED ISSUE #3: Silly comment "# Making Dictionary for dna_strs"
Comment "# Making Dictionary for dna_strs" does't provide any information. It is clear that the below line creates a dictionary with a name "dna_strs". Comment should describe what is the goal of this. e.g. Collect all cars with blue color.

### PR DESCRIPTION
**Pull request by Serwi**
Updated comment "# Making Dictionary for dna_strs"  to give information about goal of creating Dictionary below

### CODE REVIEW

**Comment by szefoski** [comment]
Name of the pull request is wrong. When you update dna.py then don't write "Update dna.py" as a title but instead of that write very short what you want to do.

**Review by szefoski — CHANGES_REQUESTED** [review]
Make the comment shorter

**Comment by Serwi** [comment]
Made comment shorter

**Comment by szefoski** [comment]
"Making Dictionary for counting strs with only necessary keys from people"

What is "strs"?

**Comment by Serwi** [comment]
A term for a tract of repetitive DNA sequence.
https://en.m.wikipedia.org/wiki/Microsatellite

**Review by szefoski — CHANGES_REQUESTED** [review]
update strs to STRs

**Pull request merged**
